viettut_admin_api:
    resource: "@ViettutAdminApiBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/admin/v1

viettut_lecturer_api:
    resource: "@ViettutUserSystemLecturerBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/lecturer/v1

viettut_api:
    resource: "@ViettutApiBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/v1

viettut_user:
    resource: "@ViettutUserBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/user/v1
