security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        Viettut\Bundles\UserBundle\Entity\User: sha512
#            algorithm: bcrypt
#            cost:      15

    role_hierarchy:
        ROLE_LECTURER: ROLE_USER
        ROLE_ADMIN:     ROLE_USER

    providers:
        viettut_user_lecturer:
            id: viettut_user_system_lecturer.user_provider.username
        viettut_user_admin:
            id: viettut_user_system_admin.user_provider.username
        viettut_user:
            chain:
                providers: [viettut_user_lecturer, viettut_user_admin]
        #
        fos_userbundle:
            id: fos_user.user_manager
#            id: fos_user.user_provider.username
#            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false

        apidoc:
            pattern:    ^/docs/?$
            security:   false

        gettoken:
            pattern:    ^/api/v1/getToken$
            stateless:  true
            gfreeau_get_jwt:
                username_parameter: username
                password_parameter: password
                post_only:          true
                success_handler:    viettut_user.handler.authentication_success
                failure_handler:    lexik_jwt_authentication.handler.authentication_failure
            provider: viettut_user

        register:
            pattern:  ^/api/user/v1/users$
            stateless: true
            security: false
            anonymous: ~

        resetting:
            pattern: ^/api/v1/resetting/
            stateless: true
            security: false
            anonymous: ~
            provider:  viettut_user_lecturer

        api:
            pattern:    ^/api/
            stateless:  true
            lexik_jwt:
                throw_exceptions:   true
                create_entry_point: false
            provider:  viettut_user

    access_control:
        - { path: ^/api/admin/, roles: ROLE_ADMIN }
        - { path: ^/api/, roles: ROLE_USER }