# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    # event dispatched on user action such as add, remove, delete
    viettut.events.handler_event: 'viettut.events.handler_event'
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    viettut.handler.handler_abstract:
        class: Viettut\Handler\HandlerAbstract
        abstract: true
        public: false
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
            - [setEvent, [%viettut.events.handler_event%]]

    # jms serializer cache
    cache.apc.jms_serializer:
        class: Doctrine\Common\Cache\ApcCache
        calls:
            - [setNamespace, ["jms_serializer"]]

    jms_serializer.metadata_cache.apc:
        class: Metadata\Cache\DoctrineCacheAdapter
        arguments:
            - ""
            - @cache.apc.jms_serializer