Viettut\Bundles\UserSystem\LecturerBundle\Entity\User:
    type:  entity
    table: core_user_lecturer

    fields:
        facebookId:
            type: bigint
            nullable: true
        googleId:
            type: string
            nullable: true
        name:
            type: string
            nullable: true
        professional:
            type: string
            nullable: true
        company:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        gender:
            type: string
            nullable: true
        city:
            type: string
            nullable: true
        state:
            type: string
            nullable: true
        address:
            type: string
            nullable: true
        postalCode:
            type: string
            nullable: true
        country:
            type: string
            nullable: true
        avatar:
            type: string
        active:
            type: boolean
            nullable: false
            options:
                default: true
        activeCode:
            type: string
            nullable: false
        settings:
            type: json_array
            nullable: true