
viettut_user_system_lecturer_security_login:
    path: /login
    defaults: { _controller: "FOSUserBundle:Security:login" }

viettut_user_system_lecturer_security_check:
    path: /login_check
    defaults: { _controller: "FOSUserBundle:Security:check" }
    methods: "POST"

viettut_user_system_lecturer_security_logout:
    path: /logout
    defaults: { _controller: "FOSUserBundle:Security:logout" }
