Viettut\Bundles\UserSystem\AdminBundle\Entity\User:
    type:  entity
    table: viettut_core_user_admin
#    id:
#        id:
#            type: integer
#            generator:
#                strategy: AUTO